export const GETTING_ALL_PLAYERS = 'GETTTING_ALL_PLAYERS';
export const GETTING_ALL_PLAYERS_SUCCESS = 'GETTING_ALL_PLAYERS_SUCCESS';
export const GETTING_ALL_PLAYERS_FAILED = 'GETTING_ALL_PLAYERS_FAILED';