export const GETTING_ALL_PLAYERS = 'GETTTING_ALL_PLAYERS';
export const GETTING_ALL_PLAYERS_SUCCESS = 'GETTING_ALL_PLAYERS_SUCCESS';
export const GETTING_ALL_PLAYERS_FAILED = 'GETTING_ALL_PLAYERS_FAILED';
export const GETTING_ALL_RESULTS = 'GETTING_ALL_RESULTS';
export const GETTING_ALL_RESULTS_SUCCESS = 'GETTING_ALL_RESULTS_SUCCESS';
export const GETTING_ALL_RESULTS_FAILED = 'GETTING_ALL_RESULTS_FAILED';
export const GETTING_ALL_CHALLENGES = 'GETTING_ALL_CHALLENGES';
export const GETTING_ALL_CHALLENGES_SUCCESS = 'GETTING_ALL_CHALLENGES_SUCCESS';
export const GETTING_ALL_CHALLENGES_FAILED = 'GETTING_ALL_CHALLENGES_FAILED';

